minecraft-server:
    ports:
        - "25565:25565"
    environment:
        EULA: "TRUE"
        VERSION: "1.7.10"
        TYPE: "FORGE"
        DIFFICULTY: "hard"
        MODE: "survival"
        PVP: "true"
        MODPACK: ""
        ONLINE_MODE: "FALSE"
    volumes:
        - ./mods:/data/mods
    image: itzg/minecraft-server:latest
    tty: true
    stdin_open: true
    restart: unless-stopped